version: "3.9"

services:
  app:
    container_name: relayer
    network_mode: host
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/app/config.json
    environment:
      - RPC_USER=crown
      - RPC_PASS=crown
      - UNLOCK_PASS=crown

